In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
tip_data=pd.read_excel('/content/tip-amount.xlsx')
tip_data.head(10)

   Meal  Observed total bill(xi)  Observed tip amount(yi)
0     1                       34                        5
1     2                      108                       17
2     3                       64                       11
3     4                       88                        8
4     5                       99                       14
5     6                       51                        5

In [2]:
tip_data.drop('Meal',axis=1,inplace=True)

In [3]:
tip_data.corr()

                         Observed total bill(xi)  Observed tip amount(yi)
Observed total bill(xi)                 1.000000                 0.865665
Observed tip amount(yi)                 0.865665                 1.000000

In [4]:
#feature- target splitting
y=tip_data['Observed tip amount(yi)']
x=tip_data.drop('Observed tip amount(yi)',axis=1)

In [5]:
# train - test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_test

   Observed total bill(xi)
0                       34
1                      108

In [6]:
#creating linear regression model
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

model=lr.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("Pred :",y_pred)
print(y_test)

Pred : [ 4.31609993 13.55968078]
0     5
1    17
Name: Observed tip amount(yi), dtype: int64

In [7]:
from sklearn.metrics import mean_squared_error,r2_score
print("MSE:",mean_squared_error(y_test,y_pred))
print("R2:",r2_score(y_test,y_pred))

MSE: 6.151757829712871
R2: 0.8291178380635313

In [21]:
import pandas as pd

# MAKING PREDICTION FOR 50$
while True:
    input_bill = int(input("\nEnter Bill Amount : "))
    bill_pred = model.predict(pd.DataFrame([[input_bill]], columns=['Observed total bill(xi)']))

    pred_df = pd.DataFrame({'Observed total bill': [input_bill], 'Predicted Tip Amount': bill_pred.flatten()})
    display(pred_df)

Enter Bill Amount : 50

   Observed total bill  Predicted Tip Amount
0                   50              6.314712

Enter Bill Amount : 40

   Observed total bill  Predicted Tip Amount
0                   40              5.065579

Enter Bill Amount : 100

   Observed total bill  Predicted Tip Amount
0                  100             12.560375

KeyboardInterrupt: Interrupted by user